import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ImageContextProvider from "@/context/ImageContext";
import { Providers } from "@/app/providers";
import ImageDimensionContextProvider from "@/context/ImageDimensionContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Dynamic Site",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ImageContextProvider>
            <ImageDimensionContextProvider>
                <html lang="en">
                    <body className={inter.className}>
                        <Providers>
                            {children}
                        </Providers>
                    </body>
                </html>
            </ImageDimensionContextProvider>
        </ImageContextProvider>
    );
}
